<a href="https://colab.research.google.com/github/yashika569384/project/blob/main/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
text_data = [

"NLP is amazing! Learning models and patterns.",

"Learning NLP is fun and powerful.",

"Deep learning improves NLP applications.",

"Text data requires cleaning and preprocessing.",

"Natural Language Processing is widely used in AI.",

"AI models learn from large amounts of text data.",

"Preprocessing text is an important step in NLP.",

"Machine learning and deep learning are related fields."

]


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:


from nltk.tokenize import word_tokenize
import string
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
def preprocess(text):
  text=text.lower()
  text=text.translate(str.maketrans('','',string.punctuation))
  tokens=word_tokenize(text)
  stemmedtoken=[stemmer.stem(word) for word in tokens]
  return " ".join(stemmedtoken)

cleaned_text=[preprocess(text) for text in text_data]




In [ ]:
print(cleaned_text)

['nlp is amaz learn model and pattern', 'learn nlp is fun and power', 'deep learn improv nlp applic', 'text data requir clean and preprocess', 'natur languag process is wide use in ai', 'ai model learn from larg amount of text data', 'preprocess text is an import step in nlp', 'machin learn and deep learn are relat field']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
bow_matrix=bow.fit_transform(cleaned_text)
print(bow_matrix.shape)


(8, 35)


In [ ]:
bow_array=bow_matrix.toarray()
print(bow_array)

[[0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1]
 [1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
t=tf.fit_transform(cleaned_text)
print(t.shape)

(8, 35)


In [ ]:
tf.vocabulary_

{'nlp': 23,
 'is': 16,
 'amaz': 1,
 'learn': 19,
 'model': 21,
 'and': 4,
 'pattern': 25,
 'fun': 12,
 'power': 26,
 'deep': 9,
 'improv': 14,
 'applic': 5,
 'text': 32,
 'data': 8,
 'requir': 30,
 'clean': 7,
 'preprocess': 27,
 'natur': 22,
 'languag': 17,
 'process': 28,
 'wide': 34,
 'use': 33,
 'in': 15,
 'ai': 0,
 'from': 11,
 'larg': 18,
 'amount': 2,
 'of': 24,
 'an': 3,
 'import': 13,
 'step': 31,
 'machin': 20,
 'are': 6,
 'relat': 29,
 'field': 10}

In [ ]:
feature_names= tf.get_feature_names_out()
print(feature_names)

['ai' 'amaz' 'amount' 'an' 'and' 'applic' 'are' 'clean' 'data' 'deep'
 'field' 'from' 'fun' 'import' 'improv' 'in' 'is' 'languag' 'larg' 'learn'
 'machin' 'model' 'natur' 'nlp' 'of' 'pattern' 'power' 'preprocess'
 'process' 'relat' 'requir' 'step' 'text' 'use' 'wide']


**bag of word**
counts how many times each word appears in a document.onverts text into numerical form by counting the frequency of each word, but it does not consider the importance or context of words.


**TF-IDF**
measures how important a word is by reducing the weight of common words and giving more weight to rare words.improves this by assigning weights to words based on their frequency in a document and their rarity across all documents, giving higher importance to meaningful words.